name: Build, Push, and Deploy to Kubernetes

on:
  push:
    branches: ['main']

env:
  REGISTRY: docker.io
  IMAGE_NAME: hritik1706/wisecow
  KUBECONFIG: ${{ secrets.KUBECONFIG }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c
        with:
          context:.
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Deploy to Kubernetes
        uses: kubernetes/deploy-action@v2
        with:
          kubeconfig: ${{ env.KUBECONFIG }}
          deployment: pod.yml
          service: service.yml
          namespace: default
