name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      run: |
        docker build -t hritik1706/wisecow:lts .
        docker push hritik1706/wisecow:lts

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Minikube
      run: |
        curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        chmod +x minikube
        sudo mv minikube /usr/local/bin/

    - name: Start Minikube
      run: |
        sudo minikube start --driver=docker
        sudo chown -R $USER ~/.minikube
        sudo chgrp -R $USER ~/.minikube
        minikube status

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'v1.21.0'

    - name: Use Minikube's Docker daemon
      run: eval $(minikube docker-env)

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f pod.yml
        kubectl apply -f service.yml

